version: 2
updates:
  # Check for React Native package updates in the client-mobile folder weekly
  - package-ecosystem: npm
    directory: /client-mobile
    schedule:
      interval: weekly

  # Check for Go package updates in the server folder weekly
  - package-ecosystem: gomod
    directory: /server-new
    schedule:
      interval: weekly

  # Check for GitHub Actions updates in the .github/workflows folder weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
