package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.42

import (
	"context"
	"fmt"
	"grocify-server/graph/model"
)

// CreateIngredient is the resolver for the createIngredient field.
func (r *mutationResolver) CreateIngredient(ctx context.Context, input model.CreateIngredientInput) (*model.Ingredient, error) {
	panic(fmt.Errorf("not implemented: CreateIngredient - createIngredient"))
}

// DeleteIngredient is the resolver for the deleteIngredient field.
func (r *mutationResolver) DeleteIngredient(ctx context.Context, id string) (*bool, error) {
	panic(fmt.Errorf("not implemented: DeleteIngredient - deleteIngredient"))
}

// UpdateIngredient is the resolver for the updateIngredient field.
func (r *mutationResolver) UpdateIngredient(ctx context.Context, id string, input model.UpdateIngredientInput) (*model.Ingredient, error) {
	panic(fmt.Errorf("not implemented: UpdateIngredient - updateIngredient"))
}

// Ingredients is the resolver for the ingredients field.
func (r *queryResolver) Ingredients(ctx context.Context) ([]*model.Ingredient, error) {
	panic(fmt.Errorf("not implemented: Ingredients - ingredients"))
}

// Ingredient is the resolver for the ingredient field.
func (r *queryResolver) Ingredient(ctx context.Context, id string) (*model.Ingredient, error) {
	panic(fmt.Errorf("not implemented: Ingredient - ingredient"))
}
