package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.42

import (
	"context"
	"fmt"
	"grocify-server/graph/model"
)

// CreateShoppingList is the resolver for the createShoppingList field.
func (r *mutationResolver) CreateShoppingList(ctx context.Context, input model.CreateShoppingListInput) (*model.ShoppingList, error) {
	panic(fmt.Errorf("not implemented: CreateShoppingList - createShoppingList"))
}

// DeleteShoppingList is the resolver for the deleteShoppingList field.
func (r *mutationResolver) DeleteShoppingList(ctx context.Context, id string) (*bool, error) {
	panic(fmt.Errorf("not implemented: DeleteShoppingList - deleteShoppingList"))
}

// UpdateShoppingList is the resolver for the updateShoppingList field.
func (r *mutationResolver) UpdateShoppingList(ctx context.Context, id string, input model.UpdateShoppingListInput) (*model.ShoppingList, error) {
	panic(fmt.Errorf("not implemented: UpdateShoppingList - updateShoppingList"))
}

// ShoppingLists is the resolver for the shoppingLists field.
func (r *queryResolver) ShoppingLists(ctx context.Context) ([]*model.ShoppingList, error) {
	panic(fmt.Errorf("not implemented: ShoppingLists - shoppingLists"))
}

// ShoppingList is the resolver for the shoppingList field.
func (r *queryResolver) ShoppingList(ctx context.Context, id string) (*model.ShoppingList, error) {
	panic(fmt.Errorf("not implemented: ShoppingList - shoppingList"))
}
