version: "3"
services:
  db:
    container_name: db
    image: postgres:13.3
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: grocify_database

  redis:
    container_name: redis
    image: redis
    command: redis-server --requirepass password
    ports:
      - 6379:6379
