[tasks.dev]
script = [
  "docker-compose -p grocify-server -f docker-compose.dev.yml up --build -d",
  "cargo watch -x run",
]

[tasks.query-metadata]
script = [
  "docker-compose -p grocify-server -f docker-compose.dev.yml up --build -d",
  "DATABASE_URL='postgresql://user:password@localhost:5432/grocify_database?sslmode=disable' cargo sqlx prepare",
]

[tasks.test-app]
script = [
  "docker-compose -p grocify-server-test -f docker-compose.test.yml up --build -d",
  "RUST_LOG=tokio=trace,sqlx=trace cargo test -- --nocapture",
]
