host = "127.0.0.1"
port = "3000"
postgres_url = "postgresql://user:password@localhost:5432/grocify_database?sslmode=disable"
test_postgres_url = "postgresql://test_user:password@localhost:5433/test_grocify_database?sslmode=disable"
redis_url = "redis://:password@localhost:6379"
test_redis_url = "redis://localhost:6380"
secret = "4378927893459802458565678578578578567858675675786785756789072347890234"
