version: "3"
services:
  server:
    build: .
    ports:
      - 80:3000
    volumes:
      - ./.env:/usr/src/app/.env # Mount the TOML file

  db:
    image: postgres:13.3
    ports:
      - 5432:5432
    env_file:
      - ./.env

  redis:
    image: redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - 6379:6379
    env_file:
      - ./.env
