version: "3"
services:
  server:
    build: .
    ports:
      - 80:3000
    depends_on:
      - db
      - redis

  db:
    image: postgres:13.3
    ports:
      - 5432:5432

  redis:
    image: redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - 6379:6379
