name: Server - build

on: [push]

permissions: read-all

jobs:
  run_server_build:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - uses: actions/checkout@v3.5.2

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Create Settings.toml
        run: |
          cat <<EOT >> ./server/Settings.toml
          host = "127.0.0.1"
          port = "3000"
          postgres_url = "postgresql://user:password@localhost:5432/grocify_database?sslmode=disable"
          test_postgres_url = "postgresql://test_user:password@localhost:5433/test_grocify_database?sslmode=disable"
          redis_url = "redis://:password@localhost:6379"
          test_redis_url = "redis://localhost:6380"
          secret = "4378927893459802458565678578578578567858675675786785756789072347890234"
          EOT

      - name: Cache cargo dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build app
        run: cargo build --release
        working-directory: ./server
