name: Server - tests

on: [push]

permissions: read-all

jobs:
  run_server_tests:
    runs-on: ubuntu-latest
    permissions: write-all

    services:
      test_db:
        image: postgres:13
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: test_grocify_database
        ports:
          - 5433:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      test_redis:
        image: redis
        ports:
          - 6380:6379
        options: --entrypoint redis-server

    steps:
      - uses: actions/checkout@v4.1.0

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Create Settings.toml
        run: |
          cat <<EOT >> ./server/Settings.toml
          host = "127.0.0.1"
          port = "3000"
          postgres_url = "postgresql://user:password@localhost:5432/grocify_database?sslmode=disable"
          test_postgres_url = "postgresql://test_user:password@localhost:5433/test_grocify_database?sslmode=disable"
          redis_url = "redis://:password@localhost:6379"
          test_redis_url = "redis://localhost:6380"
          secret = "4378927893459802458565678578578578567858675675786785756789072347890234"
          EOT

      - name: Cache cargo dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Run Tests
        run: cargo test
        working-directory: ./server
